FROM mcr.microsoft.com/dotnet/sdk:7.0 AS serverbuild

WORKDIR /app

COPY /eventLars.Server/*.csproj ./
RUN dotnet restore --disable-parallel

COPY /eventLars.Server .
RUN dotnet publish -c Release -o out --disable-parallel

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS runtime

WORKDIR /app
COPY --from=serverbuild /app/out ./

EXPOSE 5000 5001 8080 5173

ENTRYPOINT ["dotnet", "/app/eventLars.Server.dll"]