services:
  client:
    image: eventlars.client
    build:
      context: .
      dockerfile: ./Dockerfile.client
    ports:
      - 5173:5173
    container_name: eventlars.client
    volumes:
      - ${EVENTS_ROOT}:/events

networks: 
  default: 
    name: traefik 
    external: true