services:
  client:
    image: eventlars.client
    build:
      context: .
      dockerfile: ./Dockerfile.client
    ports:
      - 4173:4173
      - 5173:5173
    depends_on:
      - server

  server:
    image: eventlars.db
    mem_limit: 4g
    build:
      context: .
      dockerfile: ./Dockerfile.server
    ports:
      - 7216:7216
    volumes:
      - .:/app/events