FROM node:22-alpine AS clientbuild

WORKDIR /app
COPY /eventLars.Client/package.json .
RUN npm install

COPY /eventLars.Client/src/ ./src
COPY /eventLars.Client/static/ ./static
COPY /eventLars.Client/svelte.config.js .
COPY /eventLars.Client/tsconfig.json .
COPY /eventLars.Client/vite.config.ts .
# COPY /eventLars.Client/.svelte-kit/ .

RUN npm run build

EXPOSE 5173

ENTRYPOINT ["npm", "run", "host"]